= commune-snooze(8)

== Name

commune-snooze - manager for scheduled jobs

== Synopsis

*commune snooze* _COMMAND_

*commune snooze* enable _JOB_...

*commune snooze* disable _JOB_...

*commune snooze* run _JOB_...

*commune snooze* runner _SCRIPT_

*commune snooze* daemon _[-su]_

== Description

*commune-snooze(8)* is a tool for managing jobs running under a supervision tree. Utilizing
*snooze(1)* for running the commands and doing the job scheduling, and *s6* to supervise the jobs,
one can recreate the functionality of most *cron(8)* implementations, with additional features:

* Organized, per-job logging (thanks to *s6-log*)
* Pre-made jobs installed by packages, without being put in the same location as user configuration
  (thanks to *commune(7)*'s directory inheritance)
* Allows for randomized delays (thanks to *snooze(1)*)
* No need for ensuring multiple instances of jobs do not run (due to using supervision)
* Little chance for privilege separation issues, as there is no central daemon running the jobs.

== Design

=== Filesystem hierarchy

[listing]
--
/
├── lib
│   └── commune
│       └── snooze                      - snooze scope files
│           └── available               - jobs installed by packages, to be enabled by the user
│               └── <job>
│                   ├── run             - script generated by `commune snooze add`, ran by
│                   ├── data
│                   │   ├── command     - command ran by commune-snooze's runner
│                   │   ├── persistent  - symlink to the <job>'s persistent data directory
│                   │   └── snooze_args - arguments passed to snooze(1)
│                   ├── env             - envdir used by the job, see INHERITANCE
│                   └── log
│                       └── run
└── var
    ├── cache
    │   └── commune                     - supervision-related data that should persist across boots
    │       └── snooze
    │           └── <job>               - <job>'s persistent data directory
    │               └── snooze_timefile - see TIMEFILES in snooze(1)
    └── log
        └── commune
            └── snooze                  - job logs
                └── <job>               - s6-log directory
        │   │       ├── log
        │   │       └── run
        │   └── env                     - global envdir, used for all jobs ran on the system
        ├── system
        │   ├── available
        │   └── enabled
        └── user
            ├── available
            └── enabled
--

=== Environment directories

Environment variables are used whenever possible to avoid having to code any variables into the
execline script generated for the job. This is to aid in upgrading scripts if changes are ever
needed.

=== Inheritance

All configurations are taken in in this order

== See also

snooze(1)

https://www.skarnet.org/software/execline[skarnet's execline documentation], used for running jobs

.https://www.skarnet.org/software/s6[skarnet's s6 documentation]
* https://skarnet.org/software/s6/s6-log.html[s6-log], used for logging

include::footer.adoc[]
