= commune(7)

== Name

commune - manager of supervision trees, with scopes

== Description

commune(7) is designed as to provide an easy to use, helpful interface for which to interact with the
variety of supervision trees that one can find on Mutiny systems. Starting from being the init
system used on Mutiny, it is also used for managing scheduled jobs through snooze(1), managing user
level daemons and services, and managing user level Xorg sessions.

== Design

=== Paths

commune(7) uses a set of paths to make the supervision trees customizable and easy to integrate
package and distribution-managed policy, system configuration managed policy, and user level policy
into.

=== Static files

Static files are used for establishing the system-owned/package-owned services that are not to be
modified by users. Within the static directory for each scope, there is a set of available items
(services/jobs) that can be enabled without modification.

[listing]
--
/
├── lib
│   └── commune
│       ├── snooze                      - snooze scope files
│       │   ├── available               - jobs installed by packages, to be enabled by the user
│       │   │   └── <job>
│       │   │       ├── run             - script generated by `commune snooze add`
│       │   │       ├── data
│       │   │       │   └── persistent  - symlink to the <job>'s persistent data directory
│       │   │       ├── env             - envdir used by the job, see INHERITANCE
│       │   │       │   └── snooze_args - arguments passed to snooze(1)
│       │   │       ├── log
│       │   │       │   └── run
└── var
    ├── cache
    │   └── commune                     - supervision-related data that should persist across boots
    │       └── snooze
    │           └── <job>               - <job>'s persistent data directory
    │               └── snooze_timefile - see TIMEFILES in snooze(1)
    └── log
        └── commune
            └── snooze                  - job logs
                └── <job>               - s6-log directory
        │   │       ├── log
        │   │       └── run
        │   └── env                     - global envdir, used for all jobs ran on the system
        ├── system
        │   ├── available
        │   └── enabled
        └── user
            ├── available
            └── enabled
--

=== Environment directories

==== `commune-snooze`

Environment variables are used whenever possible to avoid having to code any variables into the
execline script generated for the job. This is to aid in upgrading scripts if changes are ever
needed.

=== Inheritance

All configurations are taken in in this order

== See also

snooze(1)

https://www.skarnet.org/software/execline[skarnet's execline documentation]

.https://www.skarnet.org/software/s6[skarnet's s6 documentation]
* https://skarnet.org/software/s6/s6-log.html[s6-log], used for logging


https://www.skarnet.org/software/s6-rc[skarnet's s6-rc documentation]

include::footer.adoc[]
