= mutiny(7)
:description: Details, overview, and other notes about the design of a Mutiny system.
:toc: right
:toclevels: 4
:sectlinks:
:sectanchors:
:idprefix:

:pp: ++

ifdef::backend-html5[]
image::logo.svg[Mutiny logo]

Mutiny is a young project! If you find the ideas here interesting, please reach out at
link:irc://irc.freenode.net/mutiny[#\mutiny@irc.freenode.net].

There's a set of https://git.somas.is/mutiny/[git repositories]. No bootable system yet, this OS
mostly exists as a pile of documents and some broken chroots for now.

This is the main document, here's a few other documents written currently:

* A short design document about <<praxis-design.7.adoc#,praxis>>, the package manager.
* A longer but unfinished document about the package API, <<theory.7.adoc#,theory>>.
* A <<software.adoc#,running list of software>> that might be of interest for Mutiny.

endif::[]

== Name

mutiny - a Linux distribution that aims to be a testbed for interesting system design, forward
thinking choices, and fun computing

== Synopsis

Mutiny is a project aiming to deliver a Linux distribution that prioritizes a consistent,
interesting, and fun to use system. Influenced heavily by minimalist software and and an interest in
forward-thinking system design, Mutiny aims to explore alternatives to the hegemony and monotony
that makes up most Linux distributions.

== Philosophy

This section will outline the intent and approach to design that Mutiny aims to have.

=== Core concepts

* **Consistency**: Unix systems have suffered from a large amount of inconsistencies
  in maintenance and style in the past decades. Software should be bent to conform, and
  users should come to expect things are going to be a certain way on a Mutiny system.
* **Alternatives**: In the Linux world there is often an acceptance that some of the system just
  sucks, and it's just what we're stuck with. And that's reasonable in some cases where alternatives
  don't exist. However, Mutiny should aim to explore, thoroughly, alternatives.
* **Documentation**: The system should be thoroughly documented so that you never need to
  reference external websites in order to learn about it. Documentation should be consistent,
  too. This means all documentation should be accessible through `man` or `/usr/share/doc`.

=== Standards adherence

:filesystem-hierarchy-standard:     http://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html
:file-hierarchy:                    https://www.freedesktop.org/software/systemd/man/file-hierarchy.html
:xdg-base-directory-specification:  https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

Mutiny should aim to adhere to standards whenever it is possible, and enforce those standards
on all software that the system uses. When a standard isn't good, or we think it is badly
designed, we should aim to supersede it with a defined standard of our own. The prime example
of a bad standard being replaced in Mutiny is the <<Filesystem layout>>, which supersedes the
{filesystem-hierarchy-standard}[Filesystem Hierarchy Standard] and systemd's
{file-hierarchy}[file-hierarchy].

Good examples of standards we want to follow would be standards like the
{xdg-base-directory-specification}[XDG Base Directory Specification].

=== System administration

The state of system administration nowadays can be very fragmented. Most people just search for the
documentation online nowadays, finding the manuals to be lacking, or just too archaic.

However, you will notice this is rarely a problem with *BSD systems. This is because BSD systems,
historically, have put more emphasis on good documentation of their systems. Every single aspect of
the kernel's internals, drivers, quirks, etc., is documented in a manpage.

On a large scale, this unity in the system is what Mutiny is striving for. Linux systems have had a
tendency to be disjointed at times, as the model which the system is developed in doesn't usually
correspond to the stewardship that comes with the tightly-managed attitude of something like OpenBSD.

Where we can best improve this is in the administration of a system.

== Prior art

* https://www.exherbo.org[Exherbo Linux] - My former distribution of choice, helped me realize the
  potential of source-based distributions; ultimately our interests diverged.
* https://www.openbsd.org[OpenBSD]
* http://sabotage.tech[Sabotage Linux]
* https://alpinelinux.org[Alpine Linux]
* https://voidlinux.eu[Void Linux]
* https://github.com/michaelforney/oasis[oasis]
* https://github.com/kissx/kiss[kiss linux]

=== Recommended reading

* https://www.openbsd.org/goals.html[OpenBSD's project goals]
* https://www.openbsd.org/policy.html[OpenBSD's copyright policy]
* https://www.youtube.com/watch?v=SGmtP5Lg_t0[Rob Landley at the Embedded Linux Conference 2013, discussing `toybox`]
* https://www.youtube.com/watch?v=04XwAbtPmAg[Rob Landley at the Embedded Linux Conference 2015, more `toybox` discussion]
* https://archive.org/details/OhioLinuxfest2013/24-Rob_Landley-The_Rise_and_Fall_of_Copyleft.flac[Rob Landley at Ohio LinuxFest 2013]
* http://hyperland.com/TedCompOneLiners[Ted Nelson's Computer Paradigm]
* https://blog.flowblok.id.au/2013-02/shell-startup-scripts.html[Shell startup scripts]

== System

:skarnet:   https://skarnet.org/software
:gnu:       https://www.gnu.org/software
:oil-shell: https://www.oilshell.org

.Software
* Prefer software with less legacy.
* Slim software whenever it is possible.
* Packages
    ** Base
        *** https://www.musl-libc.org[`musl`]
        *** https://www.libressl.org[`libressl`]
        *** http://mandoc.bsd.lv[`mandoc`]
        *** http://www.landley.net/toybox/[`toybox`]
            **** https://www.busybox.net[`busybox`] to fill in the cracks, temporarily
        *** https://www.mirbsd.org/mksh.htm[`mksh`]
            **** The long-term plan is to switch to the {oil-shell}[Oil shell] once it is fully functional
        *** {skarnet}/s6[`s6`], {skarnet}/s6-rc[`s6-rc`]
    ** Toolchain
        *** https://git.2f30.org/fortify-headers/[`fortify-headers`]
        *** https://clang.llvm.org[`clang`]
        *** https://libcxx.llvm.org[`libc{pp}`]
        *** http://invisible-island.net/byacc/byacc.html[`byacc`]
        *** https://github.com/sabotage-linux/gettext-tiny[`gettext-tiny`]

Nonessential but otherwise interesting software that would be a good fit to the philosophy can be
found on the <<software.adoc#,software page>>.

=== Mutiny utilities

* <<praxis-design.7.adoc#,`praxis`>> - a source-based package manager
* `synonym` - a utility for managing alternatives
* `commune` - utilities for working with the `s6` and `s6-rc` state manager with Mutiny policy
    ** `commune-session` - manages the login/logout actions for a user (cf. `systemd-logind`)
    ** `commune-user` - manages the user’s services and states (cf. `systemd --user`)
    ** `commune-xinit` - manages the user’s Xorg session

=== Filesystem layout

In the Mutiny layout, there are a few goals:

* Accomodate some common paths; `#!/bin/sh`, etc.
* Remove redundancy. No more `/media` or `/usr`, `/tmp` points to `/run/tmp`.
* Embrace the _good_ innovations that have occurred, like `/run` and the `/sbin`+`/bin` merge.

```
/                           - The root, and root user's home directory.
├── bin                     - System-managed binary files.
├── dev                     - Device files (devtmpfs).
├── etc                     - System-localized configuration.
├── home                    - User files.
├── include                 - System-managed header files.
├── lib                     - System-managed library files.
├── local
│   ├── bin                 - User-managed binary files.
│   ├── include             - User-managed header files.
│   ├── lib                 - User-managed library files.
│   └── share               - User managed resource files.
│       └── man             - User-managed manual pages.
├── mnt                     - Mounted devices and mountpoints.
├── proc                    - Process information (procfs).
├── run                     - Runtime files (tmpfs, directory structure created at boot).
│   ├── tmp                 - Temporary files (cleared at boot).
│   └── user                - User runtime files.
│       └── 1000            - User's `$XDG_RUNTIME_DIR` (created at login).
│           └── commune     - User's `commune` supervision trees.
│               ├── user    - Corresponds to `commune-user`, s6 tree for user's session.
│               └── xinit   - Corresponds to `commune-xinit`, s6 tree for Xorg session.
├── sbin                    - Symbolic link to `bin`.
├── share                   - Managed resource files.
│   └── man                 - System manual pages.
├── srv                     - Service directories. (git-daemon, httpd)
│   ├── git
│   └── http
├── sys                     - System/kernel information (sysfs).
├── tmp                     - Symbolic link to `run/tmp`.
├── usr                     - Symbolic link to `.`.
└── var                     - Persistent system data.
    ├── cache               - Cache for system programs.
    │   └── praxis
    │       └── distfiles   - Downloaded source for packages.
    ├── lib                 - Log files for system programs.
    ├── log                 - Databases and other data for system programs.
    ├── run                 - Symbolic link to `../run`.
    └── tmp                 - Persistent yet temporary files, not cleared at boot.
```

At one point, there was an intent to support cross-compilation, akin to Exherbo's multiarch design.
This has been removed due to a lack of necessity and ultimately, little gain for a lot of pain to
take on.

== Package design

* Reasonable command line interface
* Run (inexpensive) tests by default
* Libraries
    ** See: Gentoo's eclasses, Exherbo's exlibs
* Useful metadata
    ** Build dependencies vs. runtime dependencies
    ** Licenses
    ** Links to documentation

== Random notes

(ideally these will disappear and turn into their own sections or pages or what have you)

=== On languages and internationalization

The insistance of English being "the default language of computing" as a rationale to justify
not replacing `gettext` is rather stupid, when not a bit xenophobic. Asserting default languages
of entire fields has real world implications when it gets down to the people using them. There's a
really interesting tendency in the Unix development crowds that have minimalist design tendencies
to just ignore this.

Mutiny packages should allow for options to only install whatever languages are going to be used.
We _can_ set `en_US` as the default language that is enabled in packages, but only if we are going
to provide complete support to those who speak other languages. There's an obvious question here
as to documentation and support through things like IRC though, and I'm only one person.

=== Documentation

A goal should be to ensure that all documentation is `mdoc` format. `s6` is a notable example of a
project that doesn't currently have manpages, though I believe that's something many people in the
community have been wanting.

There's a few tools written by the main `mandoc` dev that convert other formats to mdoc, they might
be worth looking at.

* https://mandoc.bsd.lv/docbook2mdoc/[`docbook2mdoc`]
* https://mandoc.bsd.lv/pod2mdoc/[`pod2mdoc`]
* http://mandoc.bsd.lv/texi2mdoc/[`texi2mdoc`]

=== s6 based stuff

In Mutiny, a goal should be to have the same software powering many scopes of the system this
promotes the ability to have an intimate familiarity with the foundation of your system, and thus an
easier introduction to administrating it and doing cool stuff with it. A really good point in which
this can be carried out is in `s6` and `s6-rc`.

I have a work in progress implementation of doing this at the `xinit` level, since it's definitely
possible to do a supervisor as your session manager for Xorg sessions. Furthermore, this should be
able to be carried up to the login level. (call it `commune-session`, maybe) This could mean user
services for users on the system, perhaps akin to systemd's user scope...

=== Software contortions

* GNOME software
    ** https://unix.stackexchange.com/a/426348[dconf's plain text configuration method]
    ** https://developer.gnome.org/gio/stable/GSettingsBackend.html#g-keyfile-settings-backend-new[gsettings' "keyfile" backend]
    *** `GSETTINGS_BACKEND=keyfile`
    *** https://developer.gnome.org/gio/stable/GSettingsBackend.html#g-settings-backend-get-default["It is possible to override the default by setting the GSETTINGS_BACKEND environment variable to the name of a settings backend."]
* XDG contortions
    ** https://wiki.archlinux.org/index.php/XDG_Base_Directory#Partial[lots of software can be told to use XDG if you just give them the right variables]
