= software
Kylie J. McClain <kylie@somas.is>

:description: A list of software in line with the Mutiny philosophy.
:toc: right
:sectlinks:
:sectanchors:
:idprefix:

== Daemons
* https://github.com/leahneukirchen/snooze[snooze] by Leah Neukirchen could be a good
   candidate for a cron replacement. I think that could go really well with commune, perhaps
   having some sort of `commune snooze` scope to integrate with it. It's not a daemon, but their
   intended method of using `snooze` is to use it with a supervisor like `runit` (or, in our case,
   `s6`).

== Desktop
* https://github.com/TomaszGasior/gtk3-mushrooms[gtk3-mushrooms] - patches for gtk3 that make it
  nicer for non GNOME desktops. no CSD, client side shadows, and so on. though, maybe it'd be nicer
  to just avoid gtk3, if we can't do it without dbus...

* https://sourceforge.net/projects/acpid2[acpid] - not as extensive as i'd like; something like a
  real power manager type thing akin the power managers that come with MATE, GNOME, Xfce, and so on
  would be really nice
* https://github.com/troglobit/xplugd[xplugd]
* https://bitbucket.org/raymonad/xss-lock[xss-lock]
* https://github.com/Airblader/unclutter-xfixes[unclutter-xfixes]
* https://github.com/DaveDavenport/rofi[rofi]
* https://github.com/maandree/adjbacklight[adjbacklight]
* https://github.com/dunst-project/dunst[dunst] - a non-python alike would be nicer though...
* https://github.com/google/xsecurelock[xsecurelock]

== Misc
* https://www.passwordstore.org/[password-store] - something without a dependency on bash would be
  nicer though; there *are* some reimplementations/workalikes like https://github.com/nmeum/tpm[tpm]
  and https://notabug.org/kl3/spm[spm] are regular sh, but they lack a lot of features and
  niceities.
    ** https://github.com/dylanaraps/pash[pash] - appears to be more in line with what I want
* browser...?
